# Generated by Django 5.0.6 on 2024-06-10 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyAddress', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('JobDescription', models.TextField()),
                ('Salary', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Deadline', models.CharField(max_length=100)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
