# Generated by Django 5.0.6 on 2024-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0002_addjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjobmodel',
            name='CompanyAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='CompanyName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='JobDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='JobTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
